export const seedData = {
  users: {
    _model: "User",
    admin: {
      firstName: "David",
      lastName: "O' Connor",
      email: "admin@spotswap.com",
      password: "adminsecretpassword",
      role: "admin",
    },
    homer: {
      firstName: "Homer",
      lastName: "Simpson",
      email: "homer@simpson.com",
      password: "secret",
      role: "user",
    },
    marge: {
      firstName: "Marge",
      lastName: "Simpson",
      email: "marge@simpson.com",
      password: "secret",
      role: "user",
    },
    bart: {
      firstName: "Bart",
      lastName: "Simpson",
      email: "bart@simpson.com",
      password: "secret",
      role: "user",
    },
  },
  collections: {
    _model: "Collection",
    sligo: {
      title: "Best views in Sligo",
      userId: "->users.bart",
      county: "Sligo",
    },
    cong: {
      title: "Quiet Man spots in Cong",
      userId: "->users.marge",
      county: "Mayo",
    },
    belfast: {
      title: "Titanic locations in Belfast",
      userId: "->users.homer",
      county: "Antrim",
    },
    galway: {
      title: "Underrated places in Galway",
      userId: "->users.bart",
      county: "Galway",
    },
    cork: {
      title: "Best pubs in Cork",
      userId: "->users.marge",
      county: "Cork",
    },
  },
  spots: {
    _model: "Spot",
    spot_1: {
      name: "Queen Maeve Trail",
      description:
        "Spectacular views in all directions, including the Ox Mountains, Lough Gill, and Slieve League in Donegal. On a clear day, Croagh Patrick can be seen in the west.",
      latitude: 54.25326,
      longitude: -8.55774,
      collectionId: "->collections.sligo",
      category: "Nature & Outdoors",
      img: "https://res.cloudinary.com/dkfxkuklv/image/upload/v1742633365/header-queen-maeve-county-sligo_xjhfou.jpg",
    },
    spot_2: {
      name: "Quiet Man Statue",
      description: "A bronze statue of John Wayne and Maureen O'Hara.",
      latitude: 53.540515,
      longitude: -9.286646,
      collectionId: "->collections.cong",
      category: "Art & Culture",
      img: "https://res.cloudinary.com/dkfxkuklv/image/upload/v1742633432/IMG_7364-001_cac4dp.jpg",
    },
    spot_3: {
      name: "Titanic Belfast",
      description: "A visitor attraction and monument to Belfast's maritime heritage on the site of the former Harland & Wolff shipyard in the city's Titanic Quarter.",
      latitude: 54.60815,
      longitude: -5.909918,
      collectionId: "->collections.belfast",
      category: "Historical Sites",
      img: "https://res.cloudinary.com/dkfxkuklv/image/upload/v1742715569/Titanic_Belfast_HDR_fwpssc_ahyhp7.jpg",
    },
    spot_4: {
      name: "Connemara National Park",
      description: "A national park in County Galway, western Ireland.",
      latitude: 53.5486,
      longitude: -9.8852,
      collectionId: "->collections.galway",
      category: "Nature & Outdoors",
      img: "https://res.cloudinary.com/dkfxkuklv/image/upload/v1742715610/Connemara12Bens_m6a0se.jpg",
    },
    spot_5: {
      name: "Pizza Point",
      description: "Great pizza, sold by the slice",
      latitude: 53.272776,
      longitude: -9.049986,
      collectionId: "->collections.galway",
      category: "Food & Drink",
      img: "https://res.cloudinary.com/dkfxkuklv/image/upload/v1742633831/pizza-point-1200x741-1_wqagys.jpg",
    },
    spot_6: {
      name: "Circle of Life Commemorative Garden",
      description: "A beautiful stone garden beside the sea in Salthill",
      latitude: 53.25815,
      longitude: -9.086178,
      collectionId: "->collections.galway",
      category: "Nature & Outdoors",
      img: "https://res.cloudinary.com/dkfxkuklv/image/upload/v1742634055/CityParkCircleOfLife2-scaled_qf47z5.jpg",
    },
    spot_7: {
      name: "Coughlan's",
      description: "A traditional Irish pub in Cork, featuring live music.",
      latitude: 51.898,
      longitude: -8.472,
      collectionId: "->collections.cork",
      category: "Nightlife & Entertainment",
      img: "https://res.cloudinary.com/dkfxkuklv/image/upload/v1742633542/function-room-cork-coughlans-2_csrx9n.jpg",
    },
  },
};
